import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const notoSerifBengali = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
     lang="bn"
      className={`${notoSerifBengali.className} h-full antialiased`}
    >
      <body className=" flex flex-col">
        <Header></Header>
        {children}
        <Footer></Footer>
        </body>
    </html>
  );
}
